### ISSUE TITLE
can't find library

### ISSUE THREAD

**Issue by wangwl** [zanglab/bart3d#2]
Hi, very cool tool. I run into an error while trying out bart3d.  It says "Oops! No data under the library directory:", while I have the decompressed files under that path, which was downloaded as instructed. 

Thanks,
Wenliang

**Comment by zanglab** [comment]
Hi Wenliang,

Thanks for using BART3D! 

Did you modify the configure file according? Say if you download the library under  /abc/def/, then the configure file should be look like this: 
[path]
hg38_library_dir = /abc/def/
mm10_library_dir = /abc/def/

Please make sure the folder name hg38_library or mm10_library does NOT appear in the configure file.
